server {
    # Escucha en el puerto 80
    listen 80;
    listen [::]:80;
    server_name login.42.fr;

    # Redirige todo a HTTPS
    return 301 https://$host$request_uri;
}

server {

    # Escuchar en el puerto 443 para conexiones SSL (HTTPS)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Tu dominio oficial obligatorio del subject
    server_name kpineda-.42.fr;

    # Certificados SSL/TLS (Los generaremos en el Dockerfile)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocolos de seguridad exigidos por el enunciado
    ssl_protocols TLSv1.2 TLSv1.3;

    # Carpeta raíz donde estará instalado WordPress y archivo por defecto
    root /var/www/wordpress;
    index index.php index.html index.htm;

    # Regla para peticiones normales
    location / {
        try_files $uri $uri/ =404;
    }

    # Configuración crítica para que Nginx pueda hablar con WordPress (FastCGI)
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
